name: Run application

on:
  push:

jobs:
  publish:
    name: Run application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      # - name: Add credentials
      #   run: nuget sources update -Name ezzatron -username USERNAME -password "${{ secrets.GITHUB_TOKEN }}"

      - name: Restore dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet restore

      - name: Run
        run: dotnet run GitHub
