name: Run application

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Run application
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet restore
      - name: Run
        run: dotnet run
